/*
 * This source file was generated by the Gradle 'init' task
 */
package teste; 
 
public class Teste { 

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) { 
        int num1 = 3, num2 = 5, soma; 
       
      soma = num1 + num2; 
       
      } 
       
      } 