/*
 * This source file was generated by the Gradle 'init' task
 */
package aula.git.github;

public class Teste {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
